# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3MLxznecu-vsfIQrRj5KvvjvShs78Fx
"""

from google.colab import drive,files
uploaded=files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df=pd.read_excel("historical_weather_data.xlsx")

df.head()

df.tail()

df.drop('Station',axis=1,inplace=True)

df.info()

df.isnull().sum()

df.describe()

df.loc[(df['Temperature']<0.0),'WeatherCondition']='snow'

df.head()

df.tail()

df.loc[(df['Humidity']>=95.0),'WeatherCondition']='cloudy'

df.loc[(df['Precipitation']>1.0),'WeatherCondition']='rain'

df.loc[(df['Humidity']>50.0)&(df['Humidity']<95.0),'WeatherCondition']='partly cloudy'

df.loc[(df['Precipitation']==0.0)&(df['Temperature']>0.0)&(df['Humidity']<50.0),'WeatherCondition']='sunny'

df.head()

df.tail()

df.drop('WindSpeed',axis=1,inplace=True)

df.to_excel('preprocessed_data.xlsx')

